Assign Ports Programatically
ultravioletrs/cocos pull request #10
Opened 2023-10-24 02:41 UTC by WashingtonKK

Assigns ports to a vm based on availability rather than forcing.

2023-10-26 10:50 UTC, SammyOina requested changes

2023-10-26 10:50 UTC, SammyOina commented on manager/service.go
>  	// different VM guests can't forward ports to the same ports on the same host
this comment should probably move, doesn't make sense here

2023-11-10 13:02 UTC, WashingtonKK commented on manager/service.go
> +	for i := 0; i < 3; i++ {
Okay

2023-11-10 13:39 UTC, drasko requested changes

2023-11-10 13:39 UTC, drasko commented on manager/service.go
> +const (
No need for these brackets when you have only one constant. these are used to group multiple consts.

2024-01-03 07:56 UTC, SammyOina requested changes

2024-01-03 07:56 UTC, SammyOina commented on pkg/sdk/agent.go
> +
```suggestion
```
remove changes unrelated to this PR, this could be from a bad rebase

2024-01-03 07:56 UTC, SammyOina commented on pkg/sdk/agent.go
> +
```suggestion
```
remove changes unrelated to this PR, this could be from a bad rebase

2024-01-03 10:15 UTC, SammyOina approved these changes

2024-01-03 10:15 UTC, SammyOina approved these changes
Tested LGTM

2024-01-11 14:18 UTC, SammyOina commented
closed by #45

2024-01-11 14:18 UTC, closed without merging