DRAFT - Isolate the algorithm execution from Agent
ultravioletrs/cocos pull request #120
Opened 2024-04-29 14:37 UTC by danko-miladinovic

# What type of PR is this?

This PR fixes the following issues: 
#100 
#65 
## What does this do?
This PR creates a Linux Namespace for the algorithm executable so that it cannot interfere with the Agent or the kernel.

## Which issue(s) does this PR fix/relate to?
Resolves:
#100 
#65 

## Have you included tests for your changes?

The tests will be included.
## Did you document any new/modified feature?
The documentation will be updated in a separate PR to the cocos-docs repository.

### Notes

2024-05-08 09:41 UTC, dborovcanin requested changes

2024-05-08 09:41 UTC, dborovcanin commented on agent/service.go
> +
Remove unused code.

2024-05-08 09:41 UTC, dborovcanin commented on agent/service.go
> +	// new root directory
No need for this comment.

2024-05-10 13:30 UTC, danko-miladinovic commented on agent/service.go
> +
Done

2024-05-10 13:30 UTC, danko-miladinovic commented on agent/service.go
> +	// new root directory
Done

2024-05-20 14:57 UTC, dborovcanin reviewed
Is this one ready?

2024-05-20 15:25 UTC, danko-miladinovic commented
> Is this one ready?

There is a problem with `initramfs`. It cannot perform the operation `pivot_root`. I  am checking for a solution.

2024-07-06 19:56 UTC, drasko commented
Closed in favor of Docker and Wasm runtimes

2024-07-06 19:56 UTC, closed without merging