COCOS-103 - User Identification and Auth using digital signatures
ultravioletrs/cocos pull request #128
Opened 2024-05-13 11:49 UTC by SammyOina

# What type of PR is this?
This a feature as it introduces digital signatures for user authorization and identification

## What does this do?
![image](https://github.com/ultravioletrs/cocos/assets/44265300/f52249f2-3b3b-402c-a9df-0eede4785743)

- **New Features**
  - Refactored `agentSDK` struct in `pkg/sdk/agent.go` to implement the `SDK` interface with new methods for handling algorithms, data, results, and attestation.
  - Introduced functionality in `cli/keys.go` to generate RSA public/private key pairs.
  - Added private key handling in `cli/datasets.go` and `cli/result.go` for secure operations.
  - Introduced authentication and authorization features in the service with the `auth.go` file.

- **Updates**
  - Enhanced authentication and authorization features in the service with adjustments to the `auth.go` file.
  - Updated Go version to `1.22.x` in all workflows.
  - Modified the `ResultConsumers` field in `test/manual/agent-config/main.go` to enhance representation.
  - Modified the `ComputationRunReq` message in `manager/manager.proto` to use `ResultConsumer` message and added `userKey` fields to `Dataset` and `Algorithm` messages.

- **Bug Fixes**
  - Adjusted command line argument handling for better usability and security in `test/manual/README.md`.

- **Chores**
  - Added `*.pem` to `.gitignore` for better security practices.

- **Documentation**
  - Updated test instructions in `test/manual/README.md` to reflect new argument order for `algorithm-file` command.

## Which issue(s) does this PR fix/relate to?

- Resolves #103

## Have you included tests for your changes?
No

## Did you document any new/modified feature?
Yes

### Notes

2024-05-16 21:02 UTC, drasko requested changes

2024-05-16 21:02 UTC, drasko commented on agent/auth/auth.go
> +
If you added a white line here for readability, add it consistently to the upper ifs as well

2024-05-16 21:02 UTC, drasko commented on cli/keys.go
> +			pubFile, err := os.Create("public.pem")
This name of the file is a string constant, so define it before

2024-05-17 23:40 UTC, drasko approved these changes
LGTM

2024-05-17 23:40 UTC, drasko commented
@SammyOina CI is falling, please fix

2024-05-20 08:02 UTC, drasko approved these changes
LGTM

2024-05-28 12:09 UTC, dborovcanin approved these changes
Auth layer should be moved from the API closer to svc (but you don't have to move it to the service exactly), and we should have some abstractions in the form of interfaces so we can more easily test it and decouple implementation from specification.

2024-05-28 12:10 UTC, merged