DRAFT - Add CLI option to download ASK and ARK
ultravioletrs/cocos pull request #149
Opened 2024-06-14 15:06 UTC by danko-miladinovic

# What type of PR is this?
This is a feature to fetch the ASK and ARK needed to verify the attestation report. This is needed to make the attested TLS faster by not downloading the ASK and ARK from AMD KDS.

## What does this do?
Add CLI support for fetching ASK and ARK needed to verify the attestation report.

## Which issue(s) does this PR fix/relate to?

 No issue.

## Have you included tests for your changes?
Test will be added later.

## Did you document any new/modified feature?
Documentation will be added when this PR is out of draft.

### Notes

2024-06-19 12:18 UTC, SammyOina requested changes

2024-06-19 12:18 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +/*
remove commented out code

2024-06-19 12:25 UTC, danko-miladinovic commented on pkg/clients/grpc/connect.go
> +/*
Done

2024-07-03 14:02 UTC, SammyOina approved these changes

2024-07-03 14:07 UTC, merged