DRAFT: Add Agent SDK Tests
ultravioletrs/cocos pull request #167
Opened 2024-07-04 15:42 UTC by WashingtonKK

Signed-off-by: WashingtonKK <washingtonkigan@gmail.com>

# What type of PR is this?

## What does this do?

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2024-07-05 15:21 UTC, SammyOina requested changes
coverage on agent.go is about 51.9% which is quite low. Add more test cases and check on coverage using 

```shell
go test ./... -coverprofile cover.out
go tool cover -html=cover.out  
```

2024-07-08 15:02 UTC, SammyOina requested changes

2024-07-08 15:02 UTC, SammyOina commented on pkg/sdk/agent_test.go
> +				t.Errorf("expected error, got none")
Use error contains instead

2024-07-08 15:02 UTC, SammyOina commented on pkg/sdk/agent_test.go
> +			err:     errors.New("missing algorithm"),
use the errors exported from agent and wrap errors when required

2024-07-10 00:53 UTC, drasko approved these changes
LGTM

2024-07-10 00:54 UTC, drasko commented
@WashingtonKK please change according to @SammyOina 's comment and let's merge this one

2024-07-10 13:53 UTC, SammyOina approved these changes

2024-07-11 18:53 UTC, drasko approved these changes
LGTM

2024-07-11 18:53 UTC, merged