NOISSUE - Add optional Filename
ultravioletrs/cocos pull request #195
Opened 2024-08-08 11:52 UTC by SammyOina

# What type of PR is this?

## What does this do?

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2024-08-08 14:29 UTC, WashingtonKK requested changes
I am still able to upload a file with a different file name successfuily, without any error.

```
➜  cocos git:(filename) ✗ ./build/cocos-cli data test/manual/data/iris.csv private.pem                                                 
2024/08/08 17:27:25 Uploading dataset CSV: test/manual/data/iris.csv
Uploading data...  100% [============================================================================================================>] 
2024/08/08 17:27:25 Successfully uploaded dataset
```

2024-08-09 07:36 UTC, WashingtonKK commented on agent/service.go
> +	f, err := os.Create(fmt.Sprintf("%s/%s", algorithm.DatasetsDir, dataset.Filename))
Handle an instance where the filename is empty so that you do not have a dataset without a name.

2024-08-09 07:36 UTC, WashingtonKK commented on agent/service.go
> +	f, err := os.Create(fmt.Sprintf("%s/%s", algorithm.DatasetsDir, dataset.Filename))
i.e., if dataset is empty, save the dataset as dataset-1 and so on.

2024-08-09 07:37 UTC, WashingtonKK commented on agent/service.go
> +	f, err := os.Create(fmt.Sprintf("%s/%s", algorithm.DatasetsDir, dataset.Filename))
Since file is uploaded from cli, the filename can not be empty so this approach is ok.

2024-08-09 07:37 UTC, WashingtonKK approved these changes

2024-08-09 11:08 UTC, drasko reviewed
LGTM

2024-08-09 11:09 UTC, merged