NOISSUE - Add Dockerfile For IRIS Example
ultravioletrs/cocos pull request #220
Opened 2024-08-27 12:54 UTC by rodneyosodo

# What type of PR is this?

This is a feature because it adds the Dockerfile example

## What does this do?

Add Dockerfile for testing linear regression algorithm with iris dataset

## Which issue(s) does this PR fix/relate to?

No issue

## Have you included tests for your changes?

Tested manually

## Did you document any new/modified feature?

Will update documentation

### Notes

2024-08-27 13:58 UTC, danko-miladinovic approved these changes
LGTM

2024-08-27 14:30 UTC, SammyOina requested changes

2024-08-27 14:30 UTC, SammyOina commented on test/manual/algo/Dockerfile
remove the one on readme

2024-08-29 14:36 UTC, SammyOina approved these changes

2024-08-29 20:32 UTC, merged