NOISSUE - Cache and retry message sending
ultravioletrs/cocos pull request #222
Opened 2024-08-28 08:31 UTC by SammyOina

# What type of PR is this?

## What does this do?

## Which issue(s) does this PR fix/relate to?

- Related Issue #214 

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2024-08-30 13:38 UTC, dborovcanin requested changes

2024-08-30 14:16 UTC, SammyOina commented on internal/logger/protohandler.go
> +		h.w.Mu.Lock()
it is concurrent safe my mistake

2024-09-04 14:45 UTC, dborovcanin requested changes

2024-09-04 14:45 UTC, dborovcanin commented on agent/events/events.go
> +	}
Let's use a tmp map for this.

2024-09-04 14:58 UTC, dborovcanin commented on agent/events/events.go
> +	}
No need, we can simplify with something like this:
```go

func (s *service) retrySendCachedMessages() {
	s.mutex.Lock()
	defer s.mutex.Unlock()
	tmp := [][]byte{}
	for _, msg := range s.cachedMessages {
		if _, err := s.conn.Write(msg); err != nil {
			tmp = append(tmp, msg)
		}
	}
	s.cachedMessages = tmp
}
```

2024-09-04 19:09 UTC, drasko commented
@dborovcanin please follow this one and let's move it forward ASAP

2024-09-05 08:47 UTC, dborovcanin approved these changes

2024-09-06 10:55 UTC, dborovcanin requested changes

2024-09-06 10:55 UTC, dborovcanin commented on internal/logger/protohandler.go
> +	}
Why did you revert this from the discussed approach?

2024-09-06 15:02 UTC, dborovcanin approved these changes

2024-09-06 15:02 UTC, merged