fix dropping of message response from manager
ultravioletrs/cocos pull request #228
Opened 2024-09-02 21:49 UTC by SammyOina

# What type of PR is this?

## What does this do?

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

## Did you document any new/modified feature?

### Notes

2024-09-02 22:09 UTC, drasko commented
@dborovcanin needs to review this

2024-09-03 08:56 UTC, dborovcanin requested changes

2024-09-03 08:56 UTC, dborovcanin commented on manager/api/grpc/client.go
> +	client.responses <- mes
This makes this method, and all the callers, blocking if the consumer is low or stuck. We should always timeout to prevent this.

2024-09-03 09:28 UTC, dborovcanin approved these changes

2024-09-03 09:29 UTC, merged