cocos 209
ultravioletrs/cocos pull request #297
Opened 2024-11-01 12:27 UTC by WashingtonKK

- **restructure grpc configs**
- **WIP: (remove) launch.json**
- **WIP: (remove) cocos-manager.env**
- **enhance clients**

2024-11-01 12:39 UTC, SammyOina requested changes

2024-11-01 12:39 UTC, SammyOina commented on .vscode/launch.json
should not be tracked

2024-11-01 12:39 UTC, SammyOina commented on cocos-manager.env
these changes are not needed

2024-11-01 12:39 UTC, SammyOina commented on internal/server/server.go
>  	ServerCAFile string `env:"SERVER_CA_CERTS"    envDefault:""`
should be part of server base config

2024-11-01 12:39 UTC, SammyOina commented on pkg/clients/grpc/connect.go
>  }
you need cli config as well(agent client)

2024-11-01 12:39 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +func NewClient(cfg ManagerConfig) (Client, error) {
should handle both manager and agent client configs

2024-11-01 20:43 UTC, drasko commented
Fix the title

2024-11-18 12:10 UTC, SammyOina requested changes

2024-11-18 12:10 UTC, SammyOina commented on internal/server/grpc/grpc.go
> +func New(ctx context.Context, cancel context.CancelFunc, name string, config server.AgentConfig, registerService serviceRegister, logger *slog.Logger, qp client.QuoteProvider, authSvc auth.Authentica
this function is used by computations server which is different from agent, use interface type and type assertion things specific to agent server

2024-11-18 12:10 UTC, SammyOina commented on internal/server/grpc/grpc.go
> +func New(ctx context.Context, cancel context.CancelFunc, name string, config server.AgentConfig, registerService serviceRegister, logger *slog.Logger, qp client.QuoteProvider, authSvc auth.Authentica
this function is used by computations server which is different from agent, use interface type and type assertion things specific to agent server

2024-11-18 12:10 UTC, SammyOina commented on internal/server/grpc/grpc.go
> +func New(ctx context.Context, cancel context.CancelFunc, name string, config server.AgentConfig, registerService serviceRegister, logger *slog.Logger, qp client.QuoteProvider, authSvc auth.Authentica
you can create a custom interface with a method such as getBaseConfig, and then do type assertion for specific fields like attested tls

2024-11-18 12:10 UTC, SammyOina commented on internal/server/grpc/grpc.go
> +func New(ctx context.Context, cancel context.CancelFunc, name string, config server.AgentConfig, registerService serviceRegister, logger *slog.Logger, qp client.QuoteProvider, authSvc auth.Authentica
you can create a custom interface with a method such as getBaseConfig, and then do type assertion for specific fields like attested tls

2024-11-18 12:10 UTC, SammyOina commented on pkg/clients/grpc/agent/agent.go
> +func NewAgentClient(ctx context.Context, cfg server.AgentConfig) (grpc.Client, agent.AgentServiceClient, error) {
client and server config are distinct

2024-11-18 12:10 UTC, SammyOina commented on pkg/clients/grpc/agent/agent.go
> +func NewAgentClient(ctx context.Context, cfg server.AgentConfig) (grpc.Client, agent.AgentServiceClient, error) {
client and server config are distinct

2024-11-18 12:10 UTC, SammyOina commented on pkg/clients/grpc/agent/agent.go
> +func NewAgentClient(ctx context.Context, cfg server.AgentConfig) (grpc.Client, agent.AgentServiceClient, error) {
client and server config are distinct

2024-11-18 12:10 UTC, SammyOina commented on pkg/clients/grpc/agent/agent.go
> +func NewAgentClient(ctx context.Context, cfg server.AgentConfig) (grpc.Client, agent.AgentServiceClient, error) {
client and server config are distinct

2024-11-18 12:10 UTC, SammyOina commented on pkg/clients/grpc/manager/manager.go
> +	BackendInfo string `env:"BACKEND_INFO"    envDefault:""`
manager client config is not configured using backendinfo, this exclusive to agent client(CLI). also clienttls should be part of base client config

2024-11-18 12:10 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +	AttestedTLS bool   `env:"ATTESTED_TLS"       envDefault:"false"`
backendinfo and attested tls are only for agent client(CLI). This needs to bbe  distinguished. Use interfaces for configuration purposes. clienttls is common for all clients and should be part of base config

2024-11-18 12:10 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +	AttestedTLS bool   `env:"ATTESTED_TLS"       envDefault:"false"`
backendinfo and attested tls are only for agent client(CLI). This needs to bbe  distinguished. Use interfaces for configuration purposes. clienttls is common for all clients and should be part of base config

2024-11-29 11:49 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +	AttestedTLS bool `env:"ATTESTED_TLS"       envDefault:"false"`
manager cannot have attested TLS

2024-11-29 11:50 UTC, SammyOina commented on test/computations/main.go
> +	}
env only has host and port, so set url in code after parsing config

2024-11-29 11:51 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +	AttestationPolicy string `env:"ATTESTATION_POLICY" envDefault:""`
attested tls bool?

2024-11-29 11:52 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +	ClientTLS    bool          `env:"CLIENT_TLS"    envDefault:"false"`
why was this added

2024-11-29 11:52 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +	KeyFile      string        `env:"SERVER_KEY"         envDefault:""`
server certs are not used on client

2024-11-29 11:53 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +		if s.ClientTLS {
this code is breaking existing functionality

2024-12-02 14:50 UTC, SammyOina requested changes

2024-12-02 14:50 UTC, SammyOina commented on pkg/clients/grpc/connect.go
>  		}
will fail if agentconfig is any other config other than atls

2024-12-02 14:50 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +}
why do you need both client and base config, clients are only two CLI(Agent) and manager

2024-12-03 11:32 UTC, SammyOina requested changes

2024-12-03 11:32 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +		if conf.ServerCAFile != "" {
repeated in loadTLSConfig

2024-12-03 11:32 UTC, SammyOina commented on pkg/clients/grpc/connect.go
> +			if s.ServerCAFile != "" {
same here

2024-12-04 16:19 UTC, SammyOina requested changes

2024-12-04 16:19 UTC, SammyOina commented on internal/server/grpc/grpc_test.go
> +func TestServerStartWithTLS(t *testing.T) {
Do not rename the test name here

2024-12-04 16:19 UTC, SammyOina commented on internal/server/grpc/grpc_test.go
> +func TestServerStartWithMTLS(t *testing.T) {
Already in another test cas

2024-12-04 19:32 UTC, drasko approved these changes
LGTM

2024-12-04 19:32 UTC, merged