NOISSUE - Remove server
ultravioletrs/cocos pull request #76
Opened 2024-02-02 13:16 UTC by SammyOina

The manager service and client have been restructured for stream communication, facilitating real-time agent events, logs, and run responses. The `Run` RPC is replaced by the `Process` stream RPC, enabling bidirectional streaming between clients and the manager service. This allows continuous interchange of different message types including `WhoAmIRequest`, `AgentLog`, `AgentEvent`, and `RunResponse`.

Several message types have been adjusted and new fields introduced, like `AgentPort` in `RunResponse` and various agent-config attributes including CA files and instance IDs, to support TLS client authentication and distinguish between agent instances.

We've also incorporated `google.protobuf.Timestamp` in `AgentEvent` for precise event logging. The client code reflects these modifications with updated method calls and stream handling logic for ongoing communication. Moreover, the updates necessitate corresponding changes throughout service, grpc, and sdk layers to interoperate with the new streaming approach.

The transition to streaming paves the way for a more interactive, flexible communication system that can accommodate future expansion and real-time monitoring features.

2024-02-06 14:46 UTC, WashingtonKK commented on manager/service.go
> +func (ms *managerService) Run(ctx context.Context, c *ComputationRunReq) (string, error) {
Remove context

2024-02-07 09:50 UTC, SammyOina commented on manager/service.go
> +func (ms *managerService) Run(ctx context.Context, c *ComputationRunReq) (string, error) {
required for tracing

2024-02-07 09:58 UTC, WashingtonKK approved these changes
LGTM

2024-02-07 11:05 UTC, drasko requested changes

2024-02-07 11:05 UTC, drasko commented on cmd/manager/main.go
> +	if err := pc.Send(&manager.ClientStreamMessage{Message: &manager.ClientStreamMessage_WhoamiRequest{}}); err != nil {
Is this Whoami request really requests something, or is is just the notifications? Maybe I would just call it Whoami(), without `Request`.

2024-02-07 14:32 UTC, drasko approved these changes
LGTM

2024-02-07 14:32 UTC, merged