COCOS-77 - Stream agent logs and events overgRPC
ultravioletrs/cocos pull request #78
Opened 2024-02-02 13:42 UTC by SammyOina

resolves #77

2024-02-06 14:34 UTC, WashingtonKK requested changes

2024-02-06 14:34 UTC, WashingtonKK commented on cmd/manager/main.go
> +	defSvcHTTPPort = "9021"
Are these being used?

2024-02-06 14:44 UTC, SammyOina commented on cmd/manager/main.go
> +	defSvcHTTPPort = "9021"
Removed in #80

2024-02-06 15:28 UTC, WashingtonKK approved these changes
LGTM

2024-02-07 11:08 UTC, drasko approved these changes
LGTM

2024-02-07 11:08 UTC, merged